In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.shape

(4803, 4)

In [6]:
movies = movies.merge(credits , on = 'title')

In [7]:
movies.shape

(4809, 23)

In [8]:
#cols to keep 
#genres
# id : for posters display 
#genres
# keywords
# title (all in eng) 
# overview 
# cast 
#crew 
movies = movies[['movie_id' , 'title' , 'overview' , 'genres' , 'keywords' , 'cast' , 'crew']]

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [10]:
movies.isnull().sum()
#finding how many null values are there like nearly zero

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)
#drop all Nan row or columns

In [12]:
movies.duplicated().sum()

np.int64(0)

In [13]:
# for genre 
#since list was in string 
#obj is dict - [
#   {"id": 28, "name": "Action"},
#    {"id": 12, "name": "Adventure"}
#] -- where id represents genre id in dataset
def convert(obj) :
    L = [] 
    for i in ast.literal_eval(obj): 
      L.append(i['name'])
    return L 

#genre is list of words now

In [14]:
import ast

In [15]:
movies['genres'] = movies['genres'].apply(convert)

In [16]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies['keywords'] = movies['keywords'].apply(convert)

In [18]:
#considering top 3 actors 
def convert3(obj) :
    L = [] 
    counter = 0 
    for i in ast.literal_eval(obj): 
      if counter != 3:
       L.append(i['name'])
       counter += 1 
      else: 
        break 
    return L

In [19]:
movies['cast'] = movies['cast'].apply(convert3)

In [20]:
#now get director name 
def fetch_director(obj) :
    L = [] 
    for i in ast.literal_eval(obj): 
      if i['job'] == 'Director':
        L.append(i['name'])
        break 
    return L

In [21]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [22]:
#convert overview string to list 
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [23]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" " , "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" " , "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" " , "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" " , "") for i in x])

In [24]:
movies['tags'] = movies['overview'] + movies['cast'] + movies['crew']+movies['keywords'] + movies['genres']
#converting into single tag

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [26]:
new_df = movies[['movie_id' , 'title' , 'tags']]

In [27]:
new_df[['movie_id', 'title']].to_csv(
    "tmdb_movie_mapping.csv",
    index=False
)

In [28]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [29]:
#convert list to string 
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\sejal\AppData\Local\Temp\ipykernel_20236\1857227719.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [30]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. SamWorthington ZoeSaldana SigourneyWeaver JamesCameron cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d Action Adventure Fantasy ScienceFiction'

In [31]:
#convert into lowercase 
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\sejal\AppData\Local\Temp\ipykernel_20236\2760223365.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [32]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [33]:

import sys
print(sys.executable)

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

vectors = model.encode(
    new_df["tags"].tolist(),
    show_progress_bar=True
)

c:\Users\sejal\PycharmProjects\ML-proj\.venv\Scripts\python.exe

c:\Users\sejal\PycharmProjects\ML-proj\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1465.32it/s]
Batches: 100%|██████████| 151/151 [01:12<00:00,  2.07it/s]

In [34]:
vectors[0]

array([-1.92712098e-02, -1.43320691e-02, -1.03875063e-02, -7.06926733e-02,
       -8.95301700e-02, -1.65082291e-02, -6.57480489e-03, -9.97791812e-02,
        1.24738794e-02,  1.04518542e-02,  4.00443636e-02, -1.02880135e-01,
       -7.82312360e-03,  3.33239511e-02, -4.67037447e-02,  4.38507535e-02,
       -2.80412380e-02,  3.77719626e-02,  1.47417607e-02,  5.87380677e-02,
       -3.31628583e-02,  3.22639532e-02, -2.82641593e-02,  4.24563624e-02,
       -1.09933270e-02,  1.89826060e-02,  4.29459140e-02,  2.18313435e-04,
       -5.79646938e-02,  7.09477207e-03, -6.27479628e-02,  1.19533218e-01,
       -5.05987182e-02,  2.75338925e-02,  6.27091434e-03,  1.20961390e-01,
       -2.48945672e-02, -5.08807041e-02,  3.66947204e-02,  9.39782429e-03,
       -1.08957164e-01, -7.96730444e-02,  3.09613217e-02, -3.66245173e-02,
       -9.09574404e-02, -9.74051282e-02, -2.05319412e-02, -6.32434189e-02,
        7.62977675e-02,  1.59761198e-02, -1.01946563e-01, -5.03575094e-02,
       -4.31487709e-02,  7.20622204e-03,  3.64689939e-02, -1.14087313e-01,
       -4.93677109e-02,  1.95643422e-03,  1.22377379e-02, -1.58665866e-01,
        1.14956005e-02,  1.36519251e-02,  6.70152381e-02, -1.71605553e-02,
       -5.26820533e-02, -2.90230028e-02, -3.55245881e-02,  6.69209426e-03,
        4.08389606e-02, -4.69108522e-02, -2.05404535e-02,  1.25454869e-02,
       -1.32963210e-02, -1.26780821e-02, -2.24185716e-02,  6.46413565e-02,
        4.30162139e-02,  4.76241752e-04, -2.91248842e-04, -7.65786394e-02,
        1.25667661e-01,  2.45805853e-03, -6.28635287e-02,  4.59042303e-02,
       -3.64138074e-02,  2.49259863e-02,  1.38178868e-02,  4.46786955e-02,
        3.51093374e-02,  5.50183430e-02, -4.02148291e-02, -7.21307918e-02,
        3.77140455e-02, -4.98363860e-02, -6.40303567e-02, -1.48438876e-02,
       -7.13711083e-02, -1.31717352e-02, -7.02062473e-02,  3.54068987e-02,
        5.62927946e-02, -5.96731482e-03,  1.18455794e-02,  2.52950843e-02,
        4.51293923e-02, -6.76864907e-02,  2.99796443e-02, -6.42968044e-02,
       -1.17661217e-02, -3.45937796e-02, -2.16169693e-02,  4.22633812e-03,
       -9.92105380e-02,  1.98986381e-03, -3.79698910e-02,  9.94218290e-02,
       -5.88499680e-02,  1.40544912e-02,  1.11657819e-02,  2.40779817e-02,
        1.20499320e-02, -5.65333292e-02, -8.61066580e-02,  3.74012580e-03,
        3.31258662e-02, -1.21168513e-02, -4.64011505e-02,  1.71510533e-32,
        7.16933236e-02, -1.21008661e-02,  4.08917703e-02, -1.17436228e-02,
        7.51470476e-02, -2.48089712e-02, -3.46092805e-02,  2.48655919e-02,
       -8.17397609e-02, -5.55200502e-02, -1.56536728e-01, -5.87156089e-03,
       -1.19357714e-02,  3.37279700e-02, -2.02126745e-02, -4.00989689e-02,
       -3.75189744e-02, -3.46180014e-02,  3.33020790e-03, -3.52106132e-02,
       -1.83986463e-02,  2.74647791e-02, -1.02071255e-01, -6.17902763e-02,
       -1.39444107e-02, -3.82276066e-02, -3.47575136e-02, -3.02329883e-02,
        1.06402058e-02,  8.28022435e-02, -3.41551900e-02, -2.45561730e-02,
       -1.06128794e-03,  3.99044715e-03,  4.53666113e-02,  2.86303386e-02,
       -1.49737718e-02, -5.72036691e-02, -1.60078295e-02,  4.20285463e-02,
        6.65202038e-03,  7.13282153e-02, -1.31994979e-02,  9.35674682e-02,
       -5.10734096e-02, -4.16654870e-02,  1.09442882e-01,  2.19735540e-02,
        5.39950207e-02,  9.69535485e-02, -6.55453652e-02,  4.32352303e-03,
        8.82919040e-03, -4.22139987e-02,  3.02352216e-02, -5.01162037e-02,
        1.98038071e-02,  2.72103176e-02, -3.62948738e-02,  7.62156919e-02,
       -4.13382687e-02, -7.35520124e-02,  4.02768143e-03,  1.15151871e-02,
        9.94953886e-02,  2.68926099e-02,  3.86582352e-02, -1.67631507e-02,
       -3.48496027e-02, -1.58428941e-02, -9.19222832e-02, -2.77224492e-04,
        4.39341478e-02, -4.53976309e-03,  1.42471241e-02, -2.28447076e-02,
        1.24857582e-01, -9.12666917e-02,  7.96412423e-05, -6.53743148e-02,
       -7.32317269e-02, -1.60869323e-02, -7.23522110e-03,  4.84757163e-02,
       -3.15862638e-03,  1.10605145e-02,  5.01686074e-02, -3.30748484e-02,
        4.08153497e-02,  1.34015400e-02, -2.78258733e-02, -8.25711489e-02,
       -3.97486892e-03, -1.58819687e-02, -7.00136721e-02, -1.57579749e-32,
        8.69234267e-04, -3.03944647e-02, -3.78946364e-02, -5.58329113e-02,
        8.79460573e-02, -1.69044058e-03, -7.93999135e-02,  3.06984987e-02,
       -6.57983497e-02,  5.03276698e-02, -7.13357851e-02,  2.07458902e-03,
        9.50514302e-02, -1.00636883e-02, -4.38003540e-02, -4.35692221e-02,
        5.09850830e-02, -3.15025523e-02, -8.16145353e-03,  4.97150980e-02,
        6.32502371e-03,  6.48439229e-02, -3.15270945e-02, -2.97996495e-02,
        7.65014067e-03,  8.39072764e-02,  1.21028617e-01,  2.94596199e-02,
       -8.23547021e-02,  4.15649749e-02,  5.50519899e-02, -4.16618958e-02,
       -1.33384578e-02, -2.73920707e-02,  1.16699701e-02,  8.58805254e-02,
        6.99761435e-02,  2.91644433e-03, -2.43101195e-02,  9.50373523e-03,
        1.83692784e-03, -9.98677220e-03, -6.94931448e-02,  9.39448252e-02,
       -4.50479016e-02, -6.56147627e-03, -4.64125723e-03,  9.34126601e-02,
       -5.42924693e-03, -1.95839759e-02, -7.23196417e-02, -4.40515764e-03,
        3.04262135e-02,  2.03270260e-02,  2.69046612e-02,  2.15351898e-02,
       -8.33341479e-02,  1.55513519e-02,  2.30758786e-02,  3.09129152e-02,
       -1.20046420e-03, -2.24085841e-02, -5.84522868e-03,  5.37474900e-02,
       -1.68484671e-03,  3.11200861e-02,  4.29312885e-03,  1.03372566e-01,
       -1.15709476e-01,  4.40511890e-02, -1.11686392e-02, -4.63711508e-02,
       -1.27149612e-01,  1.80866309e-02,  2.80934628e-02, -2.81882230e-02,
       -5.14830649e-03, -8.17000493e-02,  2.45970618e-02,  6.68962449e-02,
        6.98603615e-02, -9.14115366e-03, -2.81437580e-02,  3.17143761e-02,
        1.05277705e-03,  5.13670668e-02,  2.01399289e-02,  1.15578830e-01,
       -7.27298856e-02,  1.06906937e-02,  2.41350662e-02,  4.41463524e-03,
       -3.35770696e-02,  2.56036315e-02,  1.63679309e-02, -6.09244069e-08,
        5.02678640e-02,  5.10896966e-02,  7.75406882e-03,  4.14743386e-02,
       -2.65374184e-02,  1.96661260e-02,  9.12449881e-03,  2.56257821e-02,
       -3.53854708e-02,  6.22640364e-02, -3.06357983e-02, -3.18442322e-02,
        4.12406251e-02, -2.17446387e-02,  2.95030624e-02,  2.06443984e-02,
        5.04682362e-02,  5.87727688e-02, -7.46792927e-02, -7.98472669e-03,
        1.26270647e-03,  1.13546767e-03,  7.48577714e-02, -9.76597518e-02,
       -3.08930855e-02,  1.35026723e-01,  4.10294421e-02, -3.05062961e-02,
       -1.38813416e-02,  5.66146933e-02,  1.98125895e-02,  2.79248916e-02,
       -1.38248950e-01, -2.84796376e-02, -8.52711573e-02, -1.41759133e-02,
       -4.62139808e-02, -5.79615729e-03,  5.71336038e-03, -3.28962202e-03,
        1.49364900e-02,  7.71540776e-02, -3.28452252e-02,  7.50315934e-02,
        4.62244265e-02,  7.59471208e-02,  9.24891904e-02, -7.86417425e-02,
        2.52812114e-02, -1.84582174e-02,  2.42572278e-02, -4.24652658e-02,
        4.17565331e-02,  3.79946232e-02,  2.07228549e-02,  6.62988275e-02,
       -2.36127526e-02,  1.20818481e-01, -1.55039309e-02,  6.07111417e-02,
        4.43264954e-02,  2.37462763e-02,  8.63033812e-03,  6.49089739e-03],
      dtype=float32)

In [37]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Collecting defusedxml (from nltk)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: click in c:\users\sejal\pycharmprojects\ml-proj\.venv\lib\site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in c:\users\sejal\pycharmprojects\ml-proj\.venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sejal\pycharmprojects\ml-proj\.venv\lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in c:\users\sejal\pycharmprojects\ml-proj\.venv\lib\site-packages (from nltk) (4.70.0)
Requirement already satisfied: colorama in c:\users\sejal\pycharmprojects\ml-proj\.venv\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------------- ---------------------- 0.8/1.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 2.8 MB/s eta 0:00:00
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Installing collected packages: defusedxml, nltk

   ---------------------------------------- 0/2 [defusedxml]
   ---------------------------------------- 0/2 [defusedxml]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   ---------------------------------------- 2/2 [nltk]

Successfully installed defusedxml-0.7.1 nltk-3.10.3

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
import nltk

C:\Users\sejal\AppData\Local\Temp\ipykernel_25680\1132361295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
similarity = cosine_similarity(vectors)
#distance with each movie

In [41]:
similarity[0]
#diagonal is always 1 movies is similar to itself

array([1.0000002 , 0.3444172 , 0.29797813, ..., 0.2116589 , 0.23977786,
       0.01859292], shape=(4806,), dtype=float32)

In [42]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index] #row in metrix
    movies_list = sorted(list(enumerate(distances)) , reverse = True , key = lambda x:x[1])[1:6]

    for i in movies_list:
       print(new_df.iloc[i[0]].title)

    #directly u cant sort si first store it as index, value pair and then sort

In [43]:
recommend('Avatar')

Serenity
Alien: Resurrection
Aliens
Invaders from Mars
Star Trek Into Darkness

In [44]:
import pickle

In [45]:
pickle.dump(new_df.to_dict() , open('movie_dict.pkl' , 'wb'))

In [46]:
pickle.dump(similarity , open('similarity.pkl' , 'wb'))
#importing ur stuff as binary file so that it can be used it without recomputing

In [47]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."